export const ADD_APPT_REQUEST = 'ADD_APPT_REQUEST';
export const ADD_APPT_SUCCESS = 'ADD_APPT_SUCCESS';
export const ADD_APPT_FAIL = 'ADD_APPT_FAIL';

export const GET_APPT_REQUEST = 'GET_APPT_REQUEST';
export const GET_APPT_SUCCESS = 'GET_APPT_SUCCESS';
export const GET_APPT_FAIL = 'GET_APPT_FAIL';
