export const VET_LOGIN_REQUEST = 'VET_LOGIN_REQUEST';
export const VET_LOGIN_SUCCESS = 'VET_LOGIN_SUCCESS';
export const VET_LOGIN_FAIL = 'VET_LOGIN_FAIL';

export const VET_REGISTER_REQUEST = 'VET_REGISTER_REQUEST';
export const VET_REGISTER_SUCCESS = 'VET_REGISTER_SUCCESS';
export const VET_REGISTER_FAIL = 'VET_REGISTER_FAIL';
